DECLARE FUNCTION BESSY! (N!, X!)
DECLARE FUNCTION BESSY0! (X!)
DECLARE FUNCTION BESSY1! (X!)

FUNCTION BESSY (N, X)
IF N < 2 THEN PRINT "bad argument N in BESSY": EXIT FUNCTION
TOX = 2! / X
BY = BESSY1(X)
BYM = BESSY0(X)
FOR J = 1 TO N - 1
  BYP = J * TOX * BY - BYM
  BYM = BY
  BY = BYP
NEXT J
BESSY = BY
END FUNCTION

