DECLARE FUNCTION BESSK! (N!, X!)
DECLARE FUNCTION BESSK0! (X!)
DECLARE FUNCTION BESSK1! (X!)

FUNCTION BESSK (N, X)
IF N < 2 THEN PRINT "bad argument N in BESSK": EXIT FUNCTION
TOX = 2! / X
BKM = BESSK0(X)
BK = BESSK1(X)
FOR J = 1 TO N - 1
  BKP = BKM + J * TOX * BK
  BKM = BK
  BK = BKP
NEXT J
BESSK = BK
END FUNCTION

