DECLARE FUNCTION BESSI! (N!, X!)
DECLARE FUNCTION BESSI0! (X!)

FUNCTION BESSI (N, X)
IACC = 40
BIGNO = 1E+10
BIGNI = 1E-10
IF N < 2 THEN PRINT "bad argument N in BESSI": EXIT FUNCTION
IF X = 0! THEN
  BESSI = 0!
ELSE
  TOX = 2! / X
  BIP = 0!
  BI = 1!
  BESI = 0!
  M = 2 * (N + INT(SQR(CSNG(IACC * N))))
  FOR J = M TO 1 STEP -1
    BIM = BIP + CSNG(J) * TOX * BI
    BIP = BI
    BI = BIM
    IF ABS(BI) > BIGNO THEN
      BESI = BESI * BIGNI
      BI = BI * BIGNI
      BIP = BIP * BIGNI
    END IF
    IF J = N THEN BESI = BIP
  NEXT J
  DUM = BESI * BESSI0(X) / BI
  IF X < 0! AND N MOD 2 = 1 THEN BESSI = -DUM ELSE BESSI = DUM
END IF
END FUNCTION

