SUB COVSRT (COVAR(), NCVM, MA, LISTA(), MFIT)
FOR J = 1 TO MA - 1
  FOR I = J + 1 TO MA
    COVAR(I, J) = 0!
  NEXT I
NEXT J
FOR I = 1 TO MFIT - 1
  FOR J = I + 1 TO MFIT
    IF LISTA(J) > LISTA(I) THEN
      COVAR(LISTA(J), LISTA(I)) = COVAR(I, J)
    ELSE
      COVAR(LISTA(I), LISTA(J)) = COVAR(I, J)
    END IF
  NEXT J
NEXT I
SWAQ = COVAR(1, 1)
FOR J = 1 TO MA
  COVAR(1, J) = COVAR(J, J)
  COVAR(J, J) = 0!
NEXT J
COVAR(LISTA(1), LISTA(1)) = SWAQ
FOR J = 2 TO MFIT
  COVAR(LISTA(J), LISTA(J)) = COVAR(1, J)
NEXT J
FOR J = 2 TO MA
  FOR I = 1 TO J - 1
    COVAR(I, J) = COVAR(J, I)
  NEXT I
NEXT J
END SUB

