DECLARE SUB DFUNC (X!(), DF!())
DECLARE FUNCTION DF1DIM! (X!)
COMMON SHARED NCOM, PCOM(), XICOM()

FUNCTION DF1DIM (X)
DIM XT(NCOM), DF(NCOM)
FOR J = 1 TO NCOM
  XT(J) = PCOM(J) + X * XICOM(J)
NEXT J
CALL DFUNC(XT(), DF())
DF1 = 0!
FOR J = 1 TO NCOM
  DF1 = DF1 + DF(J) * XICOM(J)
NEXT J
DF1DIM = DF1
ERASE DF, XT
END FUNCTION

