DECLARE FUNCTION ERFC! (X!)
DECLARE FUNCTION GAMMP! (A!, X!)
DECLARE FUNCTION GAMMQ! (A!, X!)

FUNCTION ERFC (X)
IF X < 0! THEN
  ERFC = 1! + GAMMP(.5, X ^ 2)
ELSE
  ERFC = GAMMQ(.5, X ^ 2)
END IF
END FUNCTION

