DECLARE FUNCTION EVLMEM! (FDT!, COF!(), M!, PM!)

FUNCTION EVLMEM (FDT, COF(), M, PM)
THETA# = 6.28318530717959# * FDT
WPR# = COS(THETA#)
WPI# = SIN(THETA#)
WR# = 1#
WI# = 0#
SUMR = 1!
SUMI = 0!
FOR I = 1 TO M
  WTEMP# = WR#
  WR# = WR# * WPR# - WI# * WPI#
  WI# = WI# * WPR# + WTEMP# * WPI#
  SUMR = SUMR - COF(I) * CSNG(WR#)
  SUMI = SUMI - COF(I) * CSNG(WI#)
NEXT I
EVLMEM = PM / (SUMR ^ 2 + SUMI ^ 2)
END FUNCTION

