DECLARE FUNCTION F1DIM! (X!)
DECLARE FUNCTION FUNC2! (X!(), NCOM!)
COMMON SHARED NCOM, PCOM(), XICOM()

FUNCTION F1DIM (X)
DIM XT(NCOM)
FOR J = 1 TO NCOM
  XT(J) = PCOM(J) + X * XICOM(J)
NEXT J
F1DIM = FUNC2(XT(), NCOM)
ERASE XT
END FUNCTION

