DECLARE FUNCTION FACTRL! (N!)
DECLARE FUNCTION GAMMLN! (X!)

FUNCTION FACTRL (N)
DIM A(33)
NTOP = 0
A(1) = 1!
IF N < 0 THEN
  PRINT "negative factorial"
  EXIT FUNCTION
ELSEIF N <= NTOP THEN
  FACTRL = A(N + 1)
ELSEIF N <= 32 THEN
  FOR J = NTOP + 1 TO N
    A(J + 1) = J * A(J)
  NEXT J
  NTOP = N
  FACTRL = A(N + 1)
ELSE
  FACTRL = EXP(GAMMLN(N + 1!))
END IF
END FUNCTION

