DECLARE FUNCTION FACTLN! (N!)
DECLARE FUNCTION GAMMLN! (X!)

FUNCTION FACTLN (N)
DIM A(100)
FOR I = 1 TO 100
  A(I) = -1
NEXT I
IF N < 0 THEN PRINT "negative factorial": EXIT FUNCTION
IF N <= 99 THEN
  IF A(N + 1) < 0! THEN A(N + 1) = GAMMLN(N + 1!)
  FACTLN = A(N + 1)
ELSE
  FACTLN = GAMMLN(N + 1!)
END IF
ERASE A
END FUNCTION

