DECLARE SUB GCF (GAMMCF!, A!, X!, GLN!)
DECLARE FUNCTION GAMMP! (A!, X!)
DECLARE SUB GSER (G!, A!, X!, L!)

FUNCTION GAMMP (A, X)
IF X < 0! OR A <= 0! THEN PRINT "Abnormal exit": EXIT FUNCTION
IF X < A + 1! THEN
  CALL GSER(GAMSER, A, X, GLN)
  GAMMP = GAMSER
ELSE
  CALL GCF(GAMMCF, A, X, GLN)
  GAMMP = 1! - GAMMCF
END IF
END FUNCTION

