DECLARE FUNCTION GAMMQ! (A!, X!)
DECLARE SUB GSER (GAMSER!, A!, X!, GLN!)
DECLARE SUB GCF (GAMMCF!, A!, X!, GLN!)

FUNCTION GAMMQ (A, X)
IF X < 0! OR A <= 0! THEN PRINT "Abnormal exit": EXIT FUNCTION
IF X < A + 1! THEN
  CALL GSER(GAMSER, A, X, GLN)
  GAMMQ = 1! - GAMSER
ELSE
  CALL GCF(GAMMCF, A, X, GLN)
  GAMMQ = GAMMCF
END IF
END FUNCTION

