DECLARE FUNCTION GAMMLN! (X!)

SUB GSER (GAMSER, A, X, GLN)
ITMAX = 100
EPS = .0000003
GLN = GAMMLN(A)
IF X <= 0! THEN
  IF X < 0! THEN PRINT "Abnormal exit": EXIT SUB
  GAMSER = 0!
  EXIT SUB
END IF
AP = A
SUM = 1! / A
DEL = SUM
FOR N = 1 TO ITMAX
  AP = AP + 1!
  DEL = DEL * X / AP
  SUM = SUM + DEL
  IF ABS(DEL) < ABS(SUM) * EPS THEN EXIT FOR
NEXT N
IF ABS(DEL) >= ABS(SUM) * EPS THEN
  PRINT "A too large, ITMAX too small"
  EXIT SUB
END IF
GAMSER = SUM * EXP(-X + A * LOG(X) - GLN)
END SUB

