DECLARE FUNCTION IRBIT1! (ISEED!)

FUNCTION IRBIT1 (ISEED) STATIC
IB1 = 1
IB3 = 4
IB5 = 16
IB14 = 8192
NEWBIT% = (ISEED AND IB14) <> 0
IF (ISEED AND IB5) <> 0 THEN NEWBIT% = NOT NEWBIT%
IF (ISEED AND IB3) <> 0 THEN NEWBIT% = NOT NEWBIT%
IF (ISEED AND IB1) <> 0 THEN NEWBIT% = NOT NEWBIT%
IF ISEED > 2 ^ 14 THEN ISEED = ISEED - 2 ^ 14
ISEED = 2 * ISEED
IF NEWBIT% THEN
  IRBIT1 = 1
  ISEED = ISEED OR IB1
ELSE
  IRBIT1 = 0
  ISEED = ISEED AND (NOT IB1)
END IF
END FUNCTION

