FUNCTION JULDAY& (MM, ID, IYYY)
IGREG& = 588829
IF IYYY = 0 THEN PRINT "There is no Year Zero.": EXIT FUNCTION
IF IYYY < 0 THEN IYYY = IYYY + 1
IF MM > 2 THEN
  JY = IYYY
  JM = MM + 1
ELSE
  JY = IYYY - 1
  JM = MM + 13
END IF
JD& = INT(365.25 * JY) + INT(30.6001 * JM) + ID + 1720995
IF ID + 31 * (MM + 12 * IYYY) >= IGREG& THEN
  JA = INT(.01 * JY)
  JD& = JD& + 2 - JA + INT(.25 * JA)
END IF
JULDAY& = JD&
END FUNCTION

