DECLARE SUB SORT (N!, RA!())
DECLARE FUNCTION PROBKS! (ALAM!)

SUB KSTWO (DATA1(), N1, DATA2(), N2, D, PROB)
CALL SORT(N1, DATA1())
CALL SORT(N2, DATA2())
EN1 = N1
EN2 = N2
J1 = 1
J2 = 1
FQ1 = 0!
FQ2 = 0!
D = 0!
WHILE J1 <= N1 AND J2 <= N2
  D1 = DATA1(J1)
  D2 = DATA2(J2)
  IF D1 <= D2 THEN
    FQ1 = J1 / EN1
    J1 = J1 + 1
  END IF
  IF D2 <= D1 THEN
    FQ2 = J2 / EN2
    J2 = J2 + 1
  END IF
  DT = ABS(FQ2 - FQ1)
  IF DT > D THEN D = DT
WEND
PROB = PROBKS(SQR(EN1 * EN2 / (EN1 + EN2)) * D)
END SUB

