DECLARE SUB MNBRAK (AX!, BX!, CX!, FA!, FB!, FC!, DUM!)
DECLARE FUNCTION BRENT! (AX!, BX!, CX!, DUM!, TOL!, XMIN!)
COMMON SHARED NCOM, PCOM(), XICOM()

SUB LINMIN (P(), XI(), N, FRET)
TOL = .0001
NCOM = N
FOR J = 1 TO N
  PCOM(J) = P(J)
  XICOM(J) = XI(J)
NEXT J
AX = 0!
XX = 1!
CALL MNBRAK(AX, XX, BX, FA, FX, FB, DUM)
FRET = BRENT(AX, XX, BX, DUM, TOL, XMIN)
FOR J = 1 TO N
  XI(J) = XMIN * XI(J)
  P(J) = P(J) + XI(J)
NEXT J
END SUB

