DECLARE SUB POLINT (XA!(), YA!(), N!, X!, Y!, DY!)

SUB POLIN2 (X1A(), X2A(), YA(), M, N, X1, X2, Y, DY)
DIM YNTMP(N), YMTMP(M)
FOR J = 1 TO M
  FOR K = 1 TO N
    YNTMP(K) = YA(J, K)
  NEXT K
  CALL POLINT(X2A(), YNTMP(), N, X2, YMTMP(J), DY)
NEXT J
CALL POLINT(X1A(), YMTMP(), M, X1, Y, DY)
ERASE YMTMP, YNTMP
END SUB

