SUB PREDIC (DATQ(), NDATA, D(), NPOLES, FUTURE(), NFUT)
DIM REQ(NPOLES)
FOR J = 1 TO NPOLES
  REQ(J) = DATQ(NDATA + 1 - J)
NEXT J
FOR J = 1 TO NFUT
  DISCRP = 0!
  SUM = DISCRP
  FOR K = 1 TO NPOLES
    SUM = SUM + D(K) * REQ(K)
  NEXT K
  FOR K = NPOLES TO 2 STEP -1
    REQ(K) = REQ(K - 1)
  NEXT K
  REQ(1) = SUM
  FUTURE(J) = SUM
NEXT J
ERASE REQ
END SUB

