DECLARE FUNCTION PROBKS! (ALAM!)

FUNCTION PROBKS (ALAM)
EPS1 = .001
EPS2 = 1E-08
A2 = -2! * ALAM * ALAM
FAC = 2!
DUM = 0!
TERMBF = 0!
FOR J = 1 TO 100
  TERM = FAC * EXP(A2 * J * J)
  DUM = DUM + TERM
  IF ABS(TERM) <= EPS1 * TERMBF OR ABS(TERM) <= EPS2 * DUM THEN
    PROBKS = DUM
    EXIT FUNCTION
  END IF
  FAC = -FAC
  TERMBF = ABS(TERM)
NEXT J
PROBKS = 1!
END FUNCTION

