DECLARE SUB TRAPZD (DUM!, A!, B!, S!, N!)

SUB QTRAP (DUM, A, B, S)
EPS = .000001
JMAX = 20
OLDS = -1E+30
FOR J = 1 TO JMAX
  CALL TRAPZD(DUM, A, B, S, J)
  IF ABS(S - OLDS) < EPS * ABS(OLDS) THEN EXIT SUB
  OLDS = S
NEXT J
PRINT "Too many steps."
END SUB

