DECLARE SUB QGAUSX (DUM!, A!, B!, SS!)
DECLARE SUB QGAUSY (DUM!, A!, B!, SS!)
DECLARE SUB QGAUSZ (DUM!, A!, B!, SS!)
DECLARE FUNCTION F! (ZZ!)
DECLARE FUNCTION G! (YY!)
DECLARE FUNCTION H! (XX!)
DECLARE FUNCTION Y1! (X!)
DECLARE FUNCTION Y2! (X!)
DECLARE FUNCTION Z1! (X!, Y!)
DECLARE FUNCTION Z2! (X!, Y!)
DECLARE FUNCTION FUNC! (X!, Y!, Z!)
COMMON SHARED X, Y, Z

FUNCTION F (ZZ)
Z = ZZ
F = FUNC(X, Y, Z)
END FUNCTION

FUNCTION G (YY)
Y = YY
CALL QGAUSZ(DUM, Z1(X, Y), Z2(X, Y), SS)
G = SS
END FUNCTION

FUNCTION H (XX)
X = XX
CALL QGAUSY(DUM, Y1(X), Y2(X), SS)
H = SS
END FUNCTION

SUB QUAD3D (X1, X2, SS)
CALL QGAUSX(DUM, X1, X2, SS)
END SUB

