DECLARE FUNCTION ROFUNC! (B!)
DECLARE SUB SORT (N!, RA!())
COMMON SHARED NPT, X(), Y(), ARR(), AA, ABDEV

FUNCTION ROFUNC (B)
N1 = NPT + 1
NML = INT(N1 / 2)
NMH = N1 - NML
FOR J = 1 TO NPT
  ARR(J) = Y(J) - B * X(J)
NEXT J
CALL SORT(NPT, ARR())
AA = .5 * (ARR(NML) + ARR(NMH))
SUM = 0!
ABDEV = 0!
FOR J = 1 TO NPT
  D = Y(J) - (B * X(J) + AA)
  ABDEV = ABDEV + ABS(D)
  SUM = SUM + X(J) * SGN(D)
NEXT J
ROFUNC = SUM
END FUNCTION

