DECLARE FUNCTION RTBIS! (DUM!, X1!, X2!, XACC!)
DECLARE FUNCTION FUNC! (X!)

FUNCTION RTBIS (DUM, X1, X2, XACC)
JMAX = 40
FMID = FUNC(X2)
F = FUNC(X1)
IF F * FMID >= 0! THEN
  PRINT "Root must be bracketed for bisection."
  EXIT FUNCTION
END IF
IF F < 0! THEN
  TRTBIS = X1
  DX = X2 - X1
ELSE
  TRTBIS = X2
  DX = X1 - X2
END IF
FOR J = 1 TO JMAX
  DX = DX * .5
  XMID = TRTBIS + DX
  FMID = FUNC(XMID)
  IF FMID <= 0! THEN TRTBIS = XMID
  RTBIS = TRTBIS
  IF ABS(DX) < XACC OR FMID = 0 THEN EXIT FUNCTION
NEXT J
PRINT "too many bisections"
END FUNCTION

