DECLARE SUB FUNCD (X!, FQ!, DF!)
DECLARE FUNCTION RTNEWT! (DUM!, X1!, X2!, XACC!)

FUNCTION RTNEWT (DUM, X1, X2, XACC)
JMAX = 20
TRTNEWT = .5 * (X1 + X2)
FOR J = 1 TO JMAX
  CALL FUNCD(TRTNEWT, F, DF)
  DX = F / DF
  TRTNEWT = TRTNEWT - DX
  IF (X1 - TRTNEWT) * (TRTNEWT - X2) < 0! THEN
    PRINT "jumped out of brackets"
    EXIT FUNCTION
  END IF
  RTNEWT = TRTNEWT
  IF ABS(DX) < XACC THEN EXIT FUNCTION
NEXT J
PRINT "RTNEWT exceeding maximum iterations"
END FUNCTION

