DECLARE FUNCTION RTSEC! (DUM!, X1!, X2!, XACC!)
DECLARE FUNCTION FUNC! (X!)

FUNCTION RTSEC (DUM, X1, X2, XACC)
MAXIT = 30
FL = FUNC(X1)
F = FUNC(X2)
IF ABS(FL) < ABS(F) THEN
  TRTSEC = X1
  XL = X2
  SWAP FL, F
ELSE
  XL = X1
  TRTSEC = X2
END IF
FOR J = 1 TO MAXIT
  DX = (XL - TRTSEC) * F / (F - FL)
  XL = TRTSEC
  FL = F
  TRTSEC = TRTSEC + DX
  F = FUNC(TRTSEC)
  RTSEC = TRTSEC
  IF ABS(DX) < XACC OR F = 0! THEN EXIT FUNCTION
NEXT J
PRINT "RTSEC exceed maximum iterations"
END FUNCTION

