DECLARE SUB LOAD (X1!, V!(), Y!())
DECLARE SUB SCORE (X2!, Y!(), F!())
DECLARE SUB ODEINT (YSTART!(), NVAR!, X1!, X2!, EPS!, H1!, HMIN!, NOK!, NBAD!, DUM1!, DUM2!)
DECLARE SUB LUDCMP (A!(), N!, NP!, INDX!(), D!)
DECLARE SUB LUBKSB (A!(), N!, NP!, INDX!(), B!())

SUB SHOOT (NVAR, V(), DELV(), N2, X1, X2, EPS, H1, HMIN, F(), DV())
DIM Y(NVAR), DFDV(NVAR, NVAR), INDX(NVAR)
CALL LOAD(X1, V(), Y())
CALL ODEINT(Y(), NVAR, X1, X2, EPS, H1, HMIN, NOK, NBAD, DUM, DUM)
CALL SCORE(X2, Y(), F())
FOR IV = 1 TO N2
  SAV = V(IV)
  V(IV) = V(IV) + DELV(IV)
  CALL LOAD(X1, V(), Y())
  CALL ODEINT(Y(), NVAR, X1, X2, EPS, H1, HMIN, NOK, NBAD, DUM, DUM)
  CALL SCORE(X2, Y(), DV())
  FOR I = 1 TO N2
    DFDV(I, IV) = (DV(I) - F(I)) / DELV(IV)
  NEXT I
  V(IV) = SAV
NEXT IV
FOR IV = 1 TO N2
  DV(IV) = -F(IV)
NEXT IV
CALL LUDCMP(DFDV(), N2, NVAR, INDX(), DET)
CALL LUBKSB(DFDV(), N2, NVARP, INDX(), DV())
FOR IV = 1 TO N2
  V(IV) = V(IV) + DV(IV)
NEXT IV
ERASE INDX, DFDV, Y
END SUB

