MODULE global
	USE nrtype
	IMPLICIT NONE
!	REAL(SP), PARAMETER :: T=1000.0
	REAL(SP), PARAMETER :: BBETA=5.8118
	REAL(SP), PARAMETER :: a=3480.
	REAL(SP), PARAMETER :: rs=6271.
	REAL(SP), PARAMETER :: mu=206.8166

!	REAL(SP) :: f
!	REAL(sp) :: OMEGA
END MODULE global

