MODULE global
	USE nrtype
	IMPLICIT NONE
!	REAL(SP), PARAMETER :: T=1000.0
	REAL(SP), PARAMETER :: BBETA=6.5
	REAL(SP), PARAMETER :: a=3458.0
	REAL(SP), PARAMETER :: rs=6271
	REAL(SP), PARAMETER :: mu=80

!	REAL(SP) :: f
!	REAL(sp) :: OMEGA
END MODULE global

